# Generated by Django 4.2.4 on 2023-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5, null=True, verbose_name='안내사 이름')),
                ('age', models.IntegerField(default=0, null=True, verbose_name='나이')),
                ('rate', models.IntegerField(null=True, verbose_name='받은 칭찬도장 개수')),
                ('start_date', models.DateTimeField(null=True, verbose_name='안내사 첫 시작일')),
                ('career', models.CharField(choices=[('1', '3개월 미만'), ('2', '3개월~6개월'), ('3', '6개월~1년'), ('4', '1년 이상')], default='', max_length=20, null=True, verbose_name='안내사 경력')),
                ('location', models.CharField(choices=[('1', '서울특별시'), ('2', '부산광역시')], default='', max_length=20, null=True, verbose_name='안내사 활동 가능 지역')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='img/avatar/')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('introduce', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, max_length=400, null=True, upload_to='')),
                ('last_login', models.DateField(auto_now=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
