# Generated by Django 4.2.3 on 2023-08-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='안내사 이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('rate', models.IntegerField(verbose_name='받은 칭찬도장 개수', default=0)),
                ('start_date', models.DateTimeField(verbose_name='안내사 첫 시작일')),
                ('career', models.IntegerField()),
            ],
        ),
    ]
