# Generated by Django 4.2.3 on 2023-08-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(default='', max_length=5, null=True, verbose_name='안내사 이름')),
                ('age', models.IntegerField(null=True, verbose_name='나이')),
                ('rate', models.IntegerField(default=0, null=True, verbose_name='받은 칭찬도장 개수')),
                ('start_date', models.DateTimeField(default='', null=True, verbose_name='안내사 첫 시작일')),
                ('career', models.CharField(choices=[('1', '3개월 미만'), ('2', '3개월~6개월'), ('3', '6개월~1년'), ('4', '1년 이상')], default='', max_length=20, null=True, verbose_name='안내사 경력')),
                ('location', models.CharField(choices=[('1', '서울특별시'), ('2', '부산광역시'), ('3', '대구광역시'), ('4', '인천광역시'), ('5', '광주광역시'), ('6', '대전광역시'), ('7', '울산광역시'), ('8', '세종특별자치시'), ('9', '경기도'), ('10', '강원도'), ('11', '충청북도'), ('12', '충청남도'), ('13', '전라북도'), ('14', '전라남도'), ('15', '경상북도'), ('16', '경상남도'), ('17', '제주특별자치도')], default='', max_length=20, null=True, verbose_name='안내사 활동 가능 지역')),
=======
                ('name', models.CharField(max_length=5, verbose_name='안내사 이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('rate', models.IntegerField(verbose_name='받은 칭찬도장 개수', default=0)),
                ('start_date', models.DateTimeField(verbose_name='안내사 첫 시작일')),
                ('career', models.IntegerField()),
>>>>>>> origin
            ],
        ),
    ]
