# Generated by Django 4.2.3 on 2023-08-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(choices=[('1', '2003년'), ('2', '2002년'), ('3', '2001년'), ('4', '2000년'), ('5', '1999년'), ('6', '1998년'), ('7', '1997년'), ('8', '1996년'), ('9', '1995년'), ('10', '1994년'), ('11', '1993년'), ('12', '1992년')], default=0, null=True, verbose_name='나이'),
        ),
    ]
