# Generated by Django 4.2.4 on 2023-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.DateField(null=True, verbose_name='매칭 시간'),
        ),
    ]
