# Generated by Django 4.2.4 on 2023-08-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_choice',
            field=models.CharField(choices=[('AM', '오전'), ('PM', '오후')], default='', max_length=2, null=True),
        ),
    ]
