# Generated by Django 4.2.3 on 2023-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_guidelocation_guide_location_guide_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='career',
            field=models.CharField(choices=[('1', '3개월 미만'), ('2', '3개월~6개월'), ('3', '6개월~1년'), ('4', '1년 이상')], default='seoul', max_length=20, null=True, verbose_name='안내사 경력'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='rate',
            field=models.IntegerField(default=0, null=True, verbose_name='받은 칭찬도장 개수'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='안내사 첫 시작일'),
        ),
    ]
