# Generated by Django 4.2.3 on 2023-08-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='gender',
            field=models.CharField(choices=[('1', '여자'), ('2', '남자')], max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
