# Generated by Django 4.2.3 on 2023-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_guide_age_alter_guide_career_alter_guide_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='career',
            field=models.CharField(choices=[('1', '3개월 미만'), ('2', '3개월~6개월'), ('3', '6개월~1년'), ('4', '1년 이상')], default='', max_length=20, null=True, verbose_name='안내사 경력'),
        ),
    ]
