# Generated by Django 4.2.3 on 2023-08-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_guide_gender_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='gender',
        ),
    ]
