# Generated by Django 4.2.3 on 2023-08-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='rate',
            field=models.IntegerField(null=True, verbose_name='받은 칭찬도장 개수'),
        ),
    ]
