# Generated by Django 4.2.3 on 2023-08-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='introduce',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(choices=[('1', '3개월 미만'), ('2', '3개월~6개월'), ('3', '6개월~1년'), ('4', '1년 이상')], default='', max_length=20, null=True, verbose_name='안내사 경력'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('1', '서울특별시'), ('2', '부산광역시')], default='', max_length=20, null=True, verbose_name='안내사 활동 가능 지역'),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.IntegerField(null=True, verbose_name='받은 칭찬도장 개수'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='안내사 첫 시작일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
