# Generated by Django 4.2.3 on 2023-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchuser',
            name='method',
            field=models.CharField(choices=[('quick', '빠르게찾기'), ('profile', '프로필보고찾기')], default='없음', max_length=7),
        ),
    ]
